import { z } from "zod";
import { createTool } from "@inngest/agent-kit";

import { convex } from "@/lib/convex-client";
import { api } from "../../../../../convex/_generated/api";
import { Id } from "../../../../../convex/_generated/dataModel";

interface PlanToolOptions {
  messageId: Id<"messages">;
  /**
   * Phase H — projectId is now required so the tool can ALSO mirror the plan
   * to a `PLAN.md` file in the project's file tree. Users wanted the plan
   * visible (and editable) in the editor, not only as the in-chat checklist.
   */
  projectId: Id<"projects">;
  internalKey: string;
}

/**
 * Render an array of plan steps into a Markdown checklist that lives at the
 * project root as `PLAN.md`. Mirrors the in-chat plan checklist so the user
 * can open the file, read context, and even tweak it from the editor.
 *
 * `running` becomes `- [-]` (Markdown convention for "in progress"), `done`
 * becomes `- [x]`, everything else stays `- [ ]`.
 */
const renderPlanMarkdown = (
  steps: { id: string; title: string; description?: string; status: string }[]
): string => {
  const lines: string[] = [];
  lines.push("# Plan");
  lines.push("");
  lines.push("_Auto-generated by REVDEV. Updated as the agent works through each step._");
  lines.push("");
  for (const s of steps) {
    let box = "- [ ]";
    if (s.status === "done") box = "- [x]";
    else if (s.status === "running") box = "- [-]";
    else if (s.status === "failed") box = "- [✗]";
    else if (s.status === "skipped") box = "- [~]";
    lines.push(`${box} **${s.title}**${s.description ? ` — ${s.description}` : ""}`);
  }
  lines.push("");
  return lines.join("\n");
};

/**
 * Idempotently write/replace `PLAN.md` at the project root in Convex.
 * Best-effort — if Convex hiccups we log and move on; the in-chat plan
 * checklist is still the source of truth.
 */
async function syncPlanMd(opts: {
  internalKey: string;
  projectId: Id<"projects">;
  steps: { id: string; title: string; description?: string; status: string }[];
}) {
  const content = renderPlanMarkdown(opts.steps);
  try {
    // Look for an existing PLAN.md at root level (parentId === undefined).
    const rootFiles = await convex.query(api.system.getProjectFiles, {
      internalKey: opts.internalKey,
      projectId: opts.projectId,
    });
    const existing = rootFiles.find(
      (f: { name: string; type: string; parentId?: Id<"files"> }) =>
        f.name === "PLAN.md" && f.type === "file" && !f.parentId
    );

    if (existing) {
      await convex.mutation(api.system.updateFile, {
        internalKey: opts.internalKey,
        fileId: existing._id as Id<"files">,
        content,
      });
    } else {
      await convex.mutation(api.system.createFile, {
        internalKey: opts.internalKey,
        projectId: opts.projectId,
        name: "PLAN.md",
        content,
        parentId: undefined,
      });
    }
  } catch (err) {
    console.warn("[plan tool] failed to sync PLAN.md:", err);
  }
}

// -----------------------------------------------------------------------------
// createPlan — the agent's MANDATORY first call before any other work.
// -----------------------------------------------------------------------------
export const createCreatePlanTool = ({
  messageId,
  projectId,
  internalKey,
}: PlanToolOptions) => {
  return createTool({
    name: "createPlan",
    description:
      "Create the execution plan for the user's request. CALL THIS FIRST as your very first tool call before doing any other work. Provide 3-8 short, ordered steps. Each step needs a unique id (any short string) and a concise imperative title (e.g. 'Create components/Hero.tsx').",
    parameters: z.object({
      steps: z
        .array(
          z.object({
            id: z
              .string()
              .min(1)
              .describe("Unique short identifier for this step (e.g. 'step-1' or any token)"),
            title: z
              .string()
              .min(1)
              .describe("Short imperative title shown in the UI checkbox row"),
            description: z
              .string()
              .optional()
              .describe("Optional one-line clarification (visible on hover/expand)"),
          })
        )
        .min(1, "Provide at least one step")
        .max(20, "Plans should have at most 20 steps"),
    }),
    handler: async (params, { step: toolStep }) => {
      try {
        return await toolStep?.run("create-plan", async () => {
          await convex.mutation(api.plans.createPlan, {
            internalKey,
            messageId,
            steps: params.steps,
          });

          // Phase H — also mirror to PLAN.md in the file tree so the user
          // can SEE and reference the plan from the editor, not just the
          // chat sidebar.
          await syncPlanMd({
            internalKey,
            projectId,
            steps: params.steps.map((s) => ({ ...s, status: "pending" })),
          });

          return `Plan created with ${params.steps.length} step(s) and saved to PLAN.md. Now call updatePlanStep for the first step with status="running" before you start working on it.`;
        });
      } catch (error) {
        return `Error creating plan: ${error instanceof Error ? error.message : "Unknown error"}`;
      }
    },
  });
};

// -----------------------------------------------------------------------------
// updatePlanStep — call before starting (running) and after finishing (done/failed).
// -----------------------------------------------------------------------------
export const createUpdatePlanStepTool = ({
  messageId,
  projectId,
  internalKey,
}: PlanToolOptions) => {
  return createTool({
    name: "updatePlanStep",
    description:
      "Update the status of a step in the current plan. Call with status='running' BEFORE you start a step, and status='done' (or 'failed' with an error) when finished. Use the exact step id you provided in createPlan.",
    parameters: z.object({
      stepId: z.string().describe("The id of the step to update (matches one created in createPlan)"),
      status: z
        .enum(["pending", "running", "done", "failed", "skipped"])
        .describe("New status for the step"),
      error: z
        .string()
        .optional()
        .describe("If status='failed', a one-line description of what went wrong"),
    }),
    handler: async (params, { step: toolStep }) => {
      try {
        return await toolStep?.run("update-plan-step", async () => {
          await convex.mutation(api.plans.updateStep, {
            internalKey,
            messageId,
            stepId: params.stepId,
            status: params.status,
            error: params.error,
          });

          // Phase H — re-render PLAN.md from the (now-updated) plan doc so
          // the file-tree copy stays in sync with the in-chat checklist.
          // Use the internalKey-auth'd variant since this runs in the agent
          // context (no Clerk identity).
          try {
            const plan = await convex.query(api.plans.getByMessageInternal, {
              internalKey,
              messageId,
            });
            if (plan?.steps) {
              await syncPlanMd({
                internalKey,
                projectId,
                steps: plan.steps,
              });
            }
          } catch (err) {
            console.warn("[updatePlanStep] PLAN.md re-sync failed:", err);
          }

          return `Step ${params.stepId} → ${params.status}`;
        });
      } catch (error) {
        return `Error updating plan step: ${error instanceof Error ? error.message : "Unknown error"}`;
      }
    },
  });
};
